package main

// Calibration-loop tests. The recovery test is the load-bearing one: it
// synthesizes an event stream + labelled quiz attempts from KNOWN ground-
// truth parameters (each sitting well inside the ±50% search envelope of
// the shipped values), then verifies the optimizer actually moves the
// parameters toward that truth. This is the offline analogue of Anki's
// "optimizer recovers the parameters that generated the reviews".

import (
	"math"
	"math/rand"
	"testing"
	"time"

	learning "github.com/Tencent/WeKnora/internal/application/service/learning"
	"github.com/Tencent/WeKnora/internal/types"
)

// setLearningVars writes the full calibration vector at once and returns a
// restore func.
func setLearningVars(vals map[string]float64) func() {
	table := optParamTable()
	snap := map[string]float64{}
	for _, p := range table {
		snap[p.Name] = *p.Ptr
		if v, ok := vals[p.Name]; ok {
			*p.Ptr = v
		}
	}
	return func() {
		for _, p := range optParamTable() {
			if v, ok := snap[p.Name]; ok {
				*p.Ptr = v
			}
		}
	}
}

func mustVal(t *testing.T, name string) float64 {
	t.Helper()
	for _, p := range optParamTable() {
		if p.Name == name {
			return *p.Ptr
		}
	}
	t.Fatalf("unknown param %s", name)
	return 0
}

// syntheticCorpus builds a multi-subject event stream whose quiz outcomes
// were generated by sampling from p_eff computed with the CURRENT package
// variables — so set the ground truth first, generate, then restore the
// shipped values before fitting.
//
// Streams are kept deliberately lean (one indirect touch, then alternating
// quiz answers) so that the logit at each attempt stays well below the ±4
// clamp: once the clamp saturates, different quiz weights predict nearly
// identical probabilities and the parameter becomes unidentifiable from
// that attempt. Lean streams keep every weight's signal alive.
func syntheticCorpus(seed int64) optInput {
	rng := rand.New(rand.NewSource(seed))
	base := time.Date(2026, 7, 1, 9, 0, 0, 0, time.UTC)
	var in optInput
	subjects := []string{"u1", "u2"}
	for si, subj := range subjects {
		for i := 0; i < 16; i++ {
			slug := "concept/k" + string(rune('a'+i%26)) + string(rune('0'+si))
			quizSeen := map[string]int{}
			st := learning.FoldState{}
			touch := func(evType string, at time.Time) {
				ev := types.LearningEvent{SubjectID: subj, Slug: slug, Type: evType, OccurredAt: at}
				w := refoldWeight(ev, quizSeen)
				st = learning.FoldEvent(st, learning.Event{Type: evType, Weight: w, OccurredAt: at})
				in.Events = append(in.Events, ev)
			}
			d := func(days int) time.Time { return base.AddDate(0, 0, days + si) }
			// One indirect touch, quiz-identifiable for even slugs (read,
			// weight 0.5) and cite-identifiable for odd slugs.
			if i%2 == 0 {
				touch(types.LearningEventWikiToolRead, d(0))
			} else {
				touch(types.LearningEventAnswerCite, d(0))
			}
			attempt := func(day int) {
				at := d(day)
				p := clampProb(learning.EffectiveP(st, at))
				correct := rng.Float64() < p
				in.Attempts = append(in.Attempts, types.LearningQuizAttempt{
					SubjectID: subj, Slug: slug, IsCorrect: correct, AnsweredAt: at,
				})
				evType := types.LearningEventQuizWrong
				if correct {
					evType = types.LearningEventQuizCorrect
				}
				touch(evType, at.Add(time.Minute))
			}
			attempt(1)
			attempt(3)
			attempt(5)
		}
	}
	return in
}

func TestOptimizeRecoversSyntheticTruth(t *testing.T) {
	// Ground truth: clearly off the shipped values but inside the ±50%
	// envelope the rails allow.
	truth := map[string]float64{
		"WeightQuizCorrect":   3.2, // shipped 2.2, envelope [1.1, 3.3]
		"WeightQuizWrong":     -2.1,
		"WeightAnswerCite":    1.4,
		"StabilityGrowth":     0.5,
		"StabilityLapseShrink": 0.7,
	}
	restore := setLearningVars(truth)
	corpus := syntheticCorpus(42)
	restore() // back to shipped values; now fit against the corpus

	shippedQuizCorrect := mustVal(t, "WeightQuizCorrect")
	res, err := runFit(corpus, false)
	if err != nil {
		t.Fatalf("runFit: %v", err)
	}
	if res.Attempts < 40 {
		t.Fatalf("want ≥40 labelled attempts, got %d", res.Attempts)
	}
	if res.PlainAfter >= res.PlainBefore-1e-6 {
		t.Fatalf("fitted log-loss %.4f must beat shipped %.4f", res.PlainAfter, res.PlainBefore)
	}
	// The fitted values live in res.After — live package vars are restored.
	for i, p := range res.Params {
		if want, ok := truth[p.Name]; ok {
			got := res.After[i]
			tolerance := 0.3 * math.Abs(want)
			if math.Abs(got-want) > tolerance {
				t.Errorf("%s: fitted %.3f not within ±30%% of truth %.3f", p.Name, got, want)
			}
		}
	}
	// And the shipped values must be back in the live vars after the fit.
	if got := mustVal(t, "WeightQuizCorrect"); got != shippedQuizCorrect {
		t.Fatalf("live vars not restored: QuizCorrect %.3f != %.3f", got, shippedQuizCorrect)
	}
}

func TestOptimizeConstraintsAndRestore(t *testing.T) {
	// Inverted ordering must be flagged infeasible.
	restore := setLearningVars(map[string]float64{"WeightAnswerCite": 2.0, "WeightCrossRef": 0.5})
	if paramsFeasible(optParamTable()) {
		t.Fatal("cite>cross inversion must be infeasible")
	}
	restore() // back to shipped values before fitting

	// A fit run must leave the shipped values in place afterwards.
	corpus := syntheticCorpus(7)
	if _, err := runFit(corpus, false); err != nil {
		t.Fatalf("runFit: %v", err)
	}
}

func TestOptimizeDeterministic(t *testing.T) {
	restore := setLearningVars(map[string]float64{
		"WeightQuizCorrect": 3.0,
		"StabilityGrowth":   0.45,
	})
	corpus := syntheticCorpus(11)
	restore()

	r1, err := runFit(corpus, false)
	if err != nil {
		t.Fatalf("runFit#1: %v", err)
	}
	r2, err := runFit(corpus, false)
	if err != nil {
		t.Fatalf("runFit#2: %v", err)
	}
	if math.Abs(r1.PlainAfter-r2.PlainAfter) > 1e-9 {
		t.Fatalf("non-deterministic fit: %.6f vs %.6f", r1.PlainAfter, r2.PlainAfter)
	}
}
